### ISSUE TITLE
Difficulties to upload to S3

### ISSUE THREAD

**Issue by macjl** [c33howard/signalk-to-batch-format#1]
Hello,

I’m triying to use your plugin to upload signalk data to S3.

I’m using a local S3 instance. So I created a  `.aws/credentials` file like this : 
```
[signalk]
        endpoint_url = https://aaa.xxxx.yy
        aws_access_key_id = AZERTY
        aws_access_key = AZERTYUIOPQSDFGHJKLM
        region = xx-xx
```

In the SignalK log, I just see this warning, but no more error : 
```
Nov 23 22:40:21 (node:20) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023. Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use `node --trace-warnings ...` to show where the warning was created) 
```

And nothing is uploaded to my bucket.

Is there somewhere where I can show more logs to understand what’s wrong ?

**Comment by c33howard** [comment]
Thanks for the question. I won't be able to take a look until late next week. 

When you say local S3 instance, what exactly do you mean?  Nothing uploaded is often a permissions/auth/IAM issue. You could also look at S3 access logs. 

For more verbose logs on the client, you should be able to adjust the log channels in signalk. If that's not enough and it sounds like the problem might be an AWS SDK issue, you might be able to set an environment variable to increase the verbosity. That will depend on how you're running signalk. 

Either way, sounds like I need to update the SDK version.

**Comment by macjl** [comment]
> When you say local S3 instance, what exactly do you mean? Nothing uploaded is often a permissions/auth/IAM issue. You could also look at S3 access logs.

By local, I mean a S3 not hosted in AWS, but on my own home server. I’m using minio to handle it. I will try to see if I find something in logs. 

> For more verbose logs on the client, you should be able to adjust the log channels in signalk.

I did it, but I saw no more log with or without. 

> If that's not enough and it sounds like the problem might be an AWS SDK issue, you might be able to set an environment variable to increase the verbosity. That will depend on how you're running signalk.

I’m running SignalK in docker. It’s a test instance of SignalK, so I can play with it. Do you know which env var could give me more logs ?

**Comment by c33howard** [comment]
On Fri, Nov 24, 2023 at 2:40 PM Jean-Laurent Girod ***@***.***>
wrote:

> When you say local S3 instance, what exactly do you mean? Nothing uploaded
> is often a permissions/auth/IAM issue. You could also look at S3 access
> logs.
>
> By local, I mean a S3 not hosted in AWS, but on my own home server. I’m
> using minio to handle it. I will try to see if I find something in logs.
>

Do you have a link to the server you're using?


> For more verbose logs on the client, you should be able to adjust the log
> channels in signalk.
>
> I did it, but I saw no more log with or without.
>

Here's an example log line you should see with the appropriate signalk
logging settings:

https://github.com/c33howard/signalk-to-batch-format/blob/19876d08660326e02db7a9244cba151ce1c1f6b4/index.js#L149

You'll want to turn on the channel 'signalk-to-batch-format:trace'


> If that's not enough and it sounds like the problem might be an AWS SDK
> issue, you might be able to set an environment variable to increase the
> verbosity. That will depend on how you're running signalk.
>
> I’m running SignalK in docker. It’s a test instance of SignalK, so I can
> play with it. Do you know which env var could give me more logs ?
>

Try the suggestion here:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html

**Comment by macjl** [comment]
> Do you have a link to the server you're using?

Here it is : https://min.io/

> For more verbose logs on the client, you should be able to adjust the log channels in signalkk.
> Here's an example log line you should see with the appropriate signalk logging settings: https://github.com/c33howard/signalk-to-batch-format/blob/19876d08660326e02db7a9244cba151ce1c1f6b4/index.js#L149 You'll want to turn on the channel 'signalk-to-batch-format:trace'
> If that's not enough and it sounds like the problem might be an AWS SDK issue, you might be able to set an environment variable to increase the verbosity. That will depend on how you're running signalk.
> Try the suggestion here: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html

Thank you. I now have more logs. But the problem is not clear. I can’t understand if the credential file is used or not, or if the endpoint URL is good. In the minio logs, I can’t see anything that seems to show the plugin try to connect.

```
Dec 03 08:41:24 Sun, 03 Dec 2023 07:41:24 GMT signalk-to-batch-format:trace _publish_batch 
Dec 03 08:41:24 Sun, 03 Dec 2023 07:41:24 GMT signalk-to-batch-format:trace starting upload of /home/node/.signalk/batchfiles/2023-12-03T07:40:24.033Z.json.gz to signalk/signalk/2023-12-03T07:40:24.033Z.json.gz 
Dec 03 08:41:24 [AWS s3 403 0.427s 1 retries] putObject({ Body: <Buffer 1f 8b [08 00 00 00 00 00 02](tel:08 00 00 00 00 00 02) 03 ed 5c 5b 6f 5b 37 12 7e df 5f b1 d0 b3 23 f0 32 bc f9 2d 68 16 79 69 5a 6c 1b 34 40 8a 3c a8 f6 89 2b 54 96 0c 49 76 b7 ... 3735 more bytes>, Bucket: 'signalk', Key: 'signalk/2023-12-03T07:40:24.033Z.json.gz', ContentMD5: '+w11ELkTOlaImnUWX1xXfw==', ContentEncoding: 'gzip', ContentType: 'application/json' }) 
Dec 03 08:41:24 Sun, 03 Dec 2023 07:41:24 GMT signalk-to-batch-format InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records. at Request.extractError (/home/node/.signalk/node_modules/aws-sdk/lib/services/s3.js:711:35) at Request.callListeners (/home/node/.signalk/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/home/node/.signalk/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/home/node/.signalk/node_modules/aws-sdk/lib/state_machine.js:14:12) at /home/node/.signalk/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/home/node/.signalk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) at Request.emit (/home/node/.signalk/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/home/node/.signalk/node_modules/aws-sdk/lib/state_machine.js:14:12) at /home/node/.signalk/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/home/node/.signalk/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by macjl** [comment]
I may have find the issue : 
https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-sdk-compat

The endpoint url option is only supported in AWS SDK for JS 3.x. Not in 2.x.

**Comment by c33howard** [comment]
That's probably it.  I'll take a stab at an SDK upgrade in the next few
weeks.  Patches welcome if you beat me to it.

In the short term, you can probably hack it by updating /etc/hosts to point
your bucket's domain name to localhost.  Note that I've not tested this.

**Comment by macjl** [comment]
Thank you for your proposition for a workaround with /etc/hosts, but it will not work, as my https certificate will not match the AWS URL.

**Comment by c33howard** [comment]
Funny how life gets in the way.  I've just released a new version using SDK v3.  I'll resolve this issue, feel free to reopen if needed.

**Comment by macjl** [comment]
Thank you for your work. All is working now !

Next step, I’ll try to use [signalk-from-batch-format](https://github.com/c33howard/signalk-from-batch-format) with my S3 server as source.
